name: wavenet
description: A simple wrapper for accessing Google's Text-To-Spech API and converting the results to MP3 files.
version: 2.0.5
homepage: https://github.com/jonafeucht/Flutter-WaveNet-API
repository: https://github.com/jonafeucht/Flutter-WaveNet-API

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter

  http: ">=0.13.4 <=1.0.0"
  path_provider: ">=2.0.9 <=3.0.0"

flutter:

false_secrets:
  - example/lib/main.dart